// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"lunar/internal/app/config"
	"lunar/internal/presenter/http/controller"
)

// Injectors from wire.go:

func NewWire() config.HTTPServiceInterface {
	envConfigs := config.NewViper()
	engine := config.NewGinGonic(envConfigs)
	controllerController := controller.NewController()
	logger := config.NewLogger()
	httpServiceInterface := config.NewListenApp(engine, controllerController, envConfigs, logger)
	return httpServiceInterface
}
